AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template for S3 bucket resources needed for contentify app

Parameters:
  CodePackageDate:
    Description: The date of the code package in ms.
    Type: String

Resources:
  ContentifyCodeBaseS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub contentify-code-bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  ContentifyCodeBaseS3BucketName:
    Description: Name of code base bucket
    Value: !Ref ContentifyCodeBaseS3Bucket
    Export:
      Name: !Sub contentify-code-bucket-name

  ContentifyCodeBaseS3BucketArn:
    Description: ARN of code base bucket
    Value: !GetAtt ContentifyCodeBaseS3Bucket.Arn
    Export:
      Name: !Sub contentify-code-bucket-name-arn
