package com.example.contentify.viewmodel

enum class Status {
    FINISH_GET_PDF_ITEM,
    FAIL_GET_PDF_ITEM,
    WAITING_FOR_RESPONSE,
    GET_URL_AND_JOD_ID,
    FAIL_IN_GET_URL_AND_JOD_ID,
    FAIL_UPLOAD_PDF,
    FAIL_CREATE_SUMMERY,
    FAIL_CREATE_QUESTIONS,
    FAIL_CREATE_STUDIES,
    PROCESSING_SUMMARY,
    PROCESSING_QUESTIONS,
    PROCESSING_STUDIES,
    FINISH_UPLOAD_PDF,
    FINISH_CREATE_STUDIES,
    NO_INTERNET,
    FINISH_CREATE_SUMMARY,
    FINISH_CREATE_QUESTIONS,
}